kind: ImageStreamList
apiVersion: v1
metadata: {}
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: apicast-gateway
    annotations:
      openshift.io/display-name: 3scale APIcast API Gateway
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/display-name: 3scale APIcast API Gateway (latest)
        openshift.io/provider-display-name: Red Hat, Inc.
        iconClass: icon-3scale
        description: >- 
          3scale's APIcast API Gateway is an OpenResty application which consists of two parts:
          Nginx configuration and Lua files.
          

          WARNING: By selecting this tag, your application 
          will automatically update to use the latest version of 3scale available on OpenShift,
          including major versions updates.
        tags: api,gateway,3scale
      from:
        kind: ImageStreamTag
        name: 2.1.0.GA
    - name: 2.1.0.GA
      annotations:
        openshift.io/display-name: 3scale APIcast API Gateway (latest)
        openshift.io/provider-display-name: Red Hat, Inc.
        iconClass: icon-3scale
        description: >-
          3scale's APIcast is an NGINX based API gateway used to integrate your internal and external
          API services with 3scale's API Management Platform. It supports OpenID connect to integrate
          with external Identity Providers such as Red Hat Single Sign On, for API traffic authentication.
        tags: api,gateway,3scale
        version: 2.1.0.GA
      from:
        kind: DockerImage
        name: registry.access.redhat.com/3scale-amp21/apicast-gateway:1.4-2
