apiVersion: v1
kind: Template
metadata:
  name: "amp-system-oracle"
message: "3scale AMP system Oracle Template"
objects:

- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "3scale-amp-system-oracle"
  spec:
    source:
      type: Binary
    output:
      to:
        kind: "ImageStreamTag"
        name: "amp-system:latest"

    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: "ImageStreamTag"
          name: "amp-system:${AMP_RELEASE}"


parameters:
  - name: AMP_RELEASE
    value: 2.4.0
    description: 3scale AMP release version
