diff --git Dockerfile Dockerfile
index d4c363e..bb04e22 100644
--- i/Dockerfile
+++ w/Dockerfile
@@ -7,6 +7,8 @@ COPY ./oracle-client-files/instantclient-basic*-linux.x64-12.2.*.zip \
      ./oracle-client-files/instantclient-odbc-linux.x64-12.2.*.zip \
      /opt/oracle/
 
+ADD ./workaround-non-cdb-2.4-upgrade/database.rb /opt/system/lib/system/database.rb
+
 ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_12_2/ \
     ORACLE_HOME=/opt/oracle/instantclient_12_2/ \
     DB=oracle \
